name: mechat
description: MeChat is a messaging app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.0
  cloud_firestore: ^0.14.0+2
  cupertino_icons: ^0.1.3
  equatable: ^1.2.5
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  firebase_storage: ^4.0.0
  flutter_bloc: ^6.0.0
  flutter_launcher_icons: ^0.7.5
  google_sign_in: ^4.5.3
  image_picker: ^0.6.7+7
  intl: ^0.16.1
  mockito: ^4.1.3
  numberpicker: ^1.2.1
  rubber: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ic_launcher.png"
  image_path_android: "assets/launcher/ic_launcher.png"
  adaptive_icon_background: "assets/launcher/ic_background.png"
  adaptive_icon_foreground: "assets/launcher/ic_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/launcher/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
